name: Auto-Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Auto-Merge
      id: automerge
      uses: peter-evans/auto-merge@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automatically merging"
        delete-branch: true
        labels: "merge me"
