name: Auto-Merge

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  merge:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Auto-Merge
      id: automerge
      if: github.actor == 'acemodou'
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automatically merging"
        delete-branch: true
        labels: "merge me"
