name: Unit Testing

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    # Clean up first...this is an utter bodge for self-hosted runners: https://github.community/t/how-to-properly-clean-up-self-hosted-runners/128909/6
    - name: Clean runner directory
      run: |
        echo "Cleaning up run"
        rm -rf "${{ github.workspace }}"
        mkdir "${{ github.workspace }}"
  
    - uses: actions/checkout@v3

  merge:
    if: github.actor == 'acemodou'
    runs-on: self-hosted
    steps:
    - uses: alteryx/auto-approve-pr@v1
      with:
        repository: ${{ github.repository }}
      


    
    
    
        
      

  
