name: Unit Testing

on push

jobs:
  flake8-lint:
    runs-on: self-hosted
    name: Lint 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
          python-version: "3.11"
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      
        
    
        
      

  
